#!/bin/sh

if [ "$#" -lt 10 ]; then
    echo "Usage: $0 --database <database> --user <user> --password <password> --language <language> --path <path> --package <package>"
    exit 1
fi

while [ "$#" -gt 0 ]; do
    case "$1" in
        -d|--database)
            database="$2"
            shift 2
            ;;
        -u|--user)
            user="$2"
            shift 2
            ;;
        -p|--password)
            password="$2"
            shift 2
            ;;
        -l|--language)
            language="$2"
            shift 2
            ;;
        -pt|--path)
            path="$2"
            shift 2
            ;;
        --package)
            package="$2"
            shift 2
            ;;
        *)
            echo "Invalid option: $1"
            exit 1
            ;;
    esac
done

# Vérifier si toutes les options nécessaires sont présentes
if [ -z "$database" ] || [ -z "$user" ] || [ -z "$password" ] || [ -z "$language" ] || [ -z "$path" ] || [ -z "$package" ]; then
    echo "Toutes les options (--database, --user, --password, --language, --path, --package) sont obligatoires."
    exit 1
fi


# Votre commande Java ici
java -cp "target/*" src.main.java.com.mycompany.Scaff "$database" "$user" "$password" "$language" "$path" "$package"